INITPATH=./fred/oz251/Arla/derivatives/LA

#Calculate response mean
#responsmean wm responsemean inputs output [ options ](from mrtrix readthedocs) - NEED TO BE ADJUSTED TO INCLUDE ALL PARTICIPANTS
responsemean \
-force \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-091_mrtrix_5tt_rf/sub_091_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-091_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-092_mrtrix_5tt_rf/sub_092_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-092_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-093_mrtrix_5tt_rf/sub_093_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-093_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-096_mrtrix_5tt_rf/sub_096_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-096_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-097_mrtrix_5tt_rf/sub_097_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-097_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-100_mrtrix_5tt_rf/sub_100_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-100_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-101_mrtrix_5tt_rf/sub_101_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-101_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-102_mrtrix_5tt_rf/sub_102_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-102_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-103_mrtrix_5tt_rf/sub_103_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-103_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-104_mrtrix_5tt_rf/sub_104_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-104_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-105_mrtrix_5tt_rf/sub_105_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-105_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-106_mrtrix_5tt_rf/sub_106_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-106_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-107_mrtrix_5tt_rf/sub_107_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-107_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-109_mrtrix_5tt_rf/sub_109_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-109_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-110_mrtrix_5tt_rf/sub_110_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-110_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-111_mrtrix_5tt_rf/sub_111_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-111_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-113_mrtrix_5tt_rf/sub_113_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-113_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-114_mrtrix_5tt_rf/sub_114_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-114_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-115_mrtrix_5tt_rf/sub_115_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-115_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-116_mrtrix_5tt_rf/sub_116_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-116_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-118_mrtrix_5tt_rf/sub_118_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-118_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-121_mrtrix_5tt_rf/sub_121_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-121_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-122_mrtrix_5tt_rf/sub_122_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-122_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-123_mrtrix_5tt_rf/sub_123_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-123_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-124_mrtrix_5tt_rf/sub_124_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-124_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-126_mrtrix_5tt_rf/sub_126_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-126_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-127_mrtrix_5tt_rf/sub_127_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-127_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-128_mrtrix_5tt_rf/sub_128_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-128_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-130_mrtrix_5tt_rf/sub_130_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-130_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-133_mrtrix_5tt_rf/sub_133_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-133_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-134_mrtrix_5tt_rf/sub_134_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-134_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-136_mrtrix_5tt_rf/sub_136_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-136_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-138_mrtrix_5tt_rf/sub_138_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-138_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-139_mrtrix_5tt_rf/sub_139_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-139_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-141_mrtrix_5tt_rf/sub_141_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-141_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-142_mrtrix_5tt_rf/sub_142_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-142_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-143_mrtrix_5tt_rf/sub_143_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-143_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-144_mrtrix_5tt_rf/sub_144_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-144_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-145_mrtrix_5tt_rf/sub_145_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-145_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-146_mrtrix_5tt_rf/sub_146_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-146_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-147_mrtrix_5tt_rf/sub_147_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-147_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-148_mrtrix_5tt_rf/sub_148_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-148_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-149_mrtrix_5tt_rf/sub_149_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-149_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-150_mrtrix_5tt_rf/sub_150_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-150_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-160_mrtrix_5tt_rf/sub_160_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-160_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-162_mrtrix_5tt_rf/sub_162_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-162_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-164_mrtrix_5tt_rf/sub_164_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-164_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-165_mrtrix_5tt_rf/sub_165_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-165_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-167_mrtrix_5tt_rf/sub_167_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-167_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-168_mrtrix_5tt_rf/sub_168_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-168_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-170_mrtrix_5tt_rf/sub_170_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-170_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-172_mrtrix_5tt_rf/sub_172_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-172_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-173_mrtrix_5tt_rf/sub_173_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-173_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-175_mrtrix_5tt_rf/sub_175_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-175_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-177_mrtrix_5tt_rf/sub_177_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-177_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-178_mrtrix_5tt_rf/sub_178_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-178_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-179_mrtrix_5tt_rf/sub_179_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-179_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-180_mrtrix_5tt_rf/sub_180_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-180_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-181_mrtrix_5tt_rf/sub_181_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-181_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-182_mrtrix_5tt_rf/sub_182_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-182_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-215_mrtrix_5tt_rf/sub_215_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-215_ses-1_run-1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Arla/derivatives/LA/mrtrix/connectome/responsemean_wm.txt `# output: respons mean of 2 pt. Need to be calculated for all pt's and number of unique b-values need to be identical across all input files`

#responsmean gm: responsemean inputs output [ options ] (from MRtrix readthedoc)
responsemean \
-force \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-091_mrtrix_5tt_rf/sub_091_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-091_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-092_mrtrix_5tt_rf/sub_092_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-092_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-093_mrtrix_5tt_rf/sub_093_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-093_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-096_mrtrix_5tt_rf/sub_096_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-096_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-097_mrtrix_5tt_rf/sub_097_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-097_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-100_mrtrix_5tt_rf/sub_100_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-100_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-101_mrtrix_5tt_rf/sub_101_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-101_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-102_mrtrix_5tt_rf/sub_102_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-102_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-103_mrtrix_5tt_rf/sub_103_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-103_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-104_mrtrix_5tt_rf/sub_104_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-104_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-105_mrtrix_5tt_rf/sub_105_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-105_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-106_mrtrix_5tt_rf/sub_106_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-106_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-107_mrtrix_5tt_rf/sub_107_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-107_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-109_mrtrix_5tt_rf/sub_109_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-109_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-110_mrtrix_5tt_rf/sub_110_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-110_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-111_mrtrix_5tt_rf/sub_111_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-111_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-113_mrtrix_5tt_rf/sub_113_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-113_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-114_mrtrix_5tt_rf/sub_114_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-114_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-115_mrtrix_5tt_rf/sub_115_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-115_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-116_mrtrix_5tt_rf/sub_116_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-116_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-118_mrtrix_5tt_rf/sub_118_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-118_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-121_mrtrix_5tt_rf/sub_121_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-121_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-122_mrtrix_5tt_rf/sub_122_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-122_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-123_mrtrix_5tt_rf/sub_123_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-123_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-124_mrtrix_5tt_rf/sub_124_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-124_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-126_mrtrix_5tt_rf/sub_126_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-126_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-127_mrtrix_5tt_rf/sub_127_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-127_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-128_mrtrix_5tt_rf/sub_128_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-128_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-130_mrtrix_5tt_rf/sub_130_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-130_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-133_mrtrix_5tt_rf/sub_133_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-133_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-134_mrtrix_5tt_rf/sub_134_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-134_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-136_mrtrix_5tt_rf/sub_136_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-136_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-138_mrtrix_5tt_rf/sub_138_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-138_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-139_mrtrix_5tt_rf/sub_139_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-139_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-141_mrtrix_5tt_rf/sub_141_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-141_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-142_mrtrix_5tt_rf/sub_142_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-142_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-143_mrtrix_5tt_rf/sub_143_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-143_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-144_mrtrix_5tt_rf/sub_144_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-144_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-145_mrtrix_5tt_rf/sub_145_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-145_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-146_mrtrix_5tt_rf/sub_146_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-146_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-147_mrtrix_5tt_rf/sub_147_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-147_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-148_mrtrix_5tt_rf/sub_148_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-148_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-149_mrtrix_5tt_rf/sub_149_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-149_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-150_mrtrix_5tt_rf/sub_150_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-150_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-160_mrtrix_5tt_rf/sub_160_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-160_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-162_mrtrix_5tt_rf/sub_162_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-162_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-164_mrtrix_5tt_rf/sub_164_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-164_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-165_mrtrix_5tt_rf/sub_165_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-165_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-167_mrtrix_5tt_rf/sub_167_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-167_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-168_mrtrix_5tt_rf/sub_168_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-168_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-170_mrtrix_5tt_rf/sub_170_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-170_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-172_mrtrix_5tt_rf/sub_172_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-172_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-173_mrtrix_5tt_rf/sub_173_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-173_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-175_mrtrix_5tt_rf/sub_175_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-175_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-177_mrtrix_5tt_rf/sub_177_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-177_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-178_mrtrix_5tt_rf/sub_178_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-178_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-179_mrtrix_5tt_rf/sub_179_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-179_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-180_mrtrix_5tt_rf/sub_180_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-180_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-181_mrtrix_5tt_rf/sub_181_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-181_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-182_mrtrix_5tt_rf/sub_182_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-182_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-215_mrtrix_5tt_rf/sub_215_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-215_ses-1_run-1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Arla/derivatives/LA/mrtrix/connectome/responsemean_gm.txt `# output: respons mean of 2 pt. Need to be calculated for all pt's and number of unique b-values need to be identical across all input files`

#responsmean csf: responsemean inputs output [ options ] (from MRtrix readthedoc)
responsemean \
-force \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-091_mrtrix_5tt_rf/sub_091_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-091_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-092_mrtrix_5tt_rf/sub_092_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-092_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-093_mrtrix_5tt_rf/sub_093_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-093_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-096_mrtrix_5tt_rf/sub_096_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-096_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-097_mrtrix_5tt_rf/sub_097_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-097_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-100_mrtrix_5tt_rf/sub_100_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-100_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-101_mrtrix_5tt_rf/sub_101_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-101_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-102_mrtrix_5tt_rf/sub_102_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-102_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-103_mrtrix_5tt_rf/sub_103_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-103_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-104_mrtrix_5tt_rf/sub_104_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-104_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-105_mrtrix_5tt_rf/sub_105_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-105_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-106_mrtrix_5tt_rf/sub_106_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-106_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-107_mrtrix_5tt_rf/sub_107_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-107_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-109_mrtrix_5tt_rf/sub_109_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-109_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-110_mrtrix_5tt_rf/sub_110_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-110_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-111_mrtrix_5tt_rf/sub_111_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-111_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-113_mrtrix_5tt_rf/sub_113_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-113_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-114_mrtrix_5tt_rf/sub_114_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-114_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-115_mrtrix_5tt_rf/sub_115_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-115_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-116_mrtrix_5tt_rf/sub_116_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-116_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-118_mrtrix_5tt_rf/sub_118_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-118_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-121_mrtrix_5tt_rf/sub_121_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-121_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-122_mrtrix_5tt_rf/sub_122_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-122_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-123_mrtrix_5tt_rf/sub_123_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-123_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-124_mrtrix_5tt_rf/sub_124_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-124_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-126_mrtrix_5tt_rf/sub_126_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-126_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-127_mrtrix_5tt_rf/sub_127_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-127_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-128_mrtrix_5tt_rf/sub_128_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-128_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-130_mrtrix_5tt_rf/sub_130_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-130_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-133_mrtrix_5tt_rf/sub_133_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-133_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-134_mrtrix_5tt_rf/sub_134_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-134_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-136_mrtrix_5tt_rf/sub_136_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-136_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-138_mrtrix_5tt_rf/sub_138_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-138_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-139_mrtrix_5tt_rf/sub_139_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-139_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-141_mrtrix_5tt_rf/sub_141_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-141_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-142_mrtrix_5tt_rf/sub_142_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-142_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-143_mrtrix_5tt_rf/sub_143_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-143_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-144_mrtrix_5tt_rf/sub_144_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-144_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-145_mrtrix_5tt_rf/sub_145_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-145_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-146_mrtrix_5tt_rf/sub_146_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-146_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-147_mrtrix_5tt_rf/sub_147_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-147_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-148_mrtrix_5tt_rf/sub_148_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-148_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-149_mrtrix_5tt_rf/sub_149_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-149_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-150_mrtrix_5tt_rf/sub_150_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-150_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-160_mrtrix_5tt_rf/sub_160_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-160_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-162_mrtrix_5tt_rf/sub_162_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-162_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-164_mrtrix_5tt_rf/sub_164_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-164_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-165_mrtrix_5tt_rf/sub_165_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-165_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-167_mrtrix_5tt_rf/sub_167_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-167_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-168_mrtrix_5tt_rf/sub_168_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-168_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-170_mrtrix_5tt_rf/sub_170_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-170_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-172_mrtrix_5tt_rf/sub_172_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-172_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-173_mrtrix_5tt_rf/sub_173_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-173_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-175_mrtrix_5tt_rf/sub_175_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-175_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-177_mrtrix_5tt_rf/sub_177_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-177_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-178_mrtrix_5tt_rf/sub_178_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-178_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-179_mrtrix_5tt_rf/sub_179_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-179_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-180_mrtrix_5tt_rf/sub_180_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-180_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-181_mrtrix_5tt_rf/sub_181_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-181_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-182_mrtrix_5tt_rf/sub_182_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-182_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/qsiprep/work/qsirecon_wf/sub-215_mrtrix_5tt_rf/sub_215_ses_1_run_1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-215_ses-1_run-1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Arla/derivatives/LA/mrtrix/connectome/responsemean_csf.txt `# output: respons mean of 2 pt. Need to be calculated for all pt's and number of unique b-values need to be identical across all input files`

#look at the meanRF (from BATMAN) - NEED TO BE ADJUSTED TO INCLUDE ALL PARTICIPANTS
shview /fred/oz251/Arla/derivatives/LA/mrtrix/connectome/responsemean_wm.txt `# Path/to_meanresponsfunction`
shview /fred/oz251/Arla/derivatives/LA/mrtrix/connectome/responsemean_gm.txt `# Path/to_meanresponsfunction`
shview /fred/oz251/Arla/derivatives/LA/mrtrix/connectome/responsemean_csf.txt `# Path/to_meanresponsfunction`
