#Calculate response mean
#responsmean wm: responsemean inputs output [ options ] (from MRtrix readthedoc)
responsemean \
-force \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-301_mrtrix_5tt_rf/sub_301_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-301_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-302_mrtrix_5tt_rf/sub_302_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-302_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-303_mrtrix_5tt_rf/sub_303_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-303_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-304_mrtrix_5tt_rf/sub_304_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-304_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-305_mrtrix_5tt_rf/sub_305_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-305_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-306_mrtrix_5tt_rf/sub_306_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-306_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-307_mrtrix_5tt_rf/sub_307_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-307_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-308_mrtrix_5tt_rf/sub_308_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-308_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-309_mrtrix_5tt_rf/sub_309_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-309_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-310_mrtrix_5tt_rf/sub_310_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-310_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-311_mrtrix_5tt_rf/sub_311_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-311_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-312_mrtrix_5tt_rf/sub_312_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-312_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-314_mrtrix_5tt_rf/sub_314_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-314_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-315_mrtrix_5tt_rf/sub_315_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-315_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-316_mrtrix_5tt_rf/sub_316_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-316_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-352_mrtrix_5tt_rf/sub_352_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-352_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-353_mrtrix_5tt_rf/sub_353_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-353_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-358_mrtrix_5tt_rf/sub_358_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-358_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-361_mrtrix_5tt_rf/sub_361_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-361_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-362_mrtrix_5tt_rf/sub_362_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-362_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-363_mrtrix_5tt_rf/sub_363_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-363_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-364_mrtrix_5tt_rf/sub_364_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-364_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-365_mrtrix_5tt_rf/sub_365_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-365_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-366_mrtrix_5tt_rf/sub_366_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-366_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-367_mrtrix_5tt_rf/sub_367_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-367_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-368_mrtrix_5tt_rf/sub_368_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-368_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-369_mrtrix_5tt_rf/sub_369_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-369_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-501_mrtrix_5tt_rf/sub_501_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-501_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-502_mrtrix_5tt_rf/sub_502_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-502_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-503_mrtrix_5tt_rf/sub_503_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-503_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-504_mrtrix_5tt_rf/sub_504_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-504_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-505_mrtrix_5tt_rf/sub_505_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-505_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-506_mrtrix_5tt_rf/sub_506_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-506_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-507_mrtrix_5tt_rf/sub_507_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-507_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-508_mrtrix_5tt_rf/sub_508_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-508_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-509_mrtrix_5tt_rf/sub_509_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-509_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-510_mrtrix_5tt_rf/sub_510_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-510_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-512_mrtrix_5tt_rf/sub_512_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-512_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-513_mrtrix_5tt_rf/sub_513_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-513_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-514_mrtrix_5tt_rf/sub_514_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-514_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-515_mrtrix_5tt_rf/sub_515_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-515_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-551_mrtrix_5tt_rf/sub_551_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-551_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-553_mrtrix_5tt_rf/sub_553_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-553_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-555_mrtrix_5tt_rf/sub_555_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-555_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-556_mrtrix_5tt_rf/sub_556_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-556_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-557_mrtrix_5tt_rf/sub_557_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-557_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-558_mrtrix_5tt_rf/sub_558_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-558_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-559_mrtrix_5tt_rf/sub_559_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-559_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-560_mrtrix_5tt_rf/sub_560_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-560_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-561_mrtrix_5tt_rf/sub_561_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-561_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-562_mrtrix_5tt_rf/sub_562_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-562_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-563_mrtrix_5tt_rf/sub_563_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-563_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-564_mrtrix_5tt_rf/sub_564_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-564_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-565_mrtrix_5tt_rf/sub_565_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-565_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-611_mrtrix_5tt_rf/sub_611_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-611_ses-V1_space-T1w_desc-preproc_dwi_wm.txt \
/fred/oz251/Mast/derivatives/LA/mrtrix/connectome/responsemean_wm.txt `# output: respons mean of 2 pt. Need to be calculated for all pt's and number of unique b-values need to be identical across all input files`

#responsmean gm responsemean inputs output [ options ](from mrtrix readthedocs) - NEED TO BE ADJUSTED TO INCLUDE ALL PARTICIPANTS
responsemean \
-force \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-301_mrtrix_5tt_rf/sub_301_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-301_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-302_mrtrix_5tt_rf/sub_302_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-302_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-303_mrtrix_5tt_rf/sub_303_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-303_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-304_mrtrix_5tt_rf/sub_304_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-304_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-305_mrtrix_5tt_rf/sub_305_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-305_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-306_mrtrix_5tt_rf/sub_306_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-306_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-307_mrtrix_5tt_rf/sub_307_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-307_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-308_mrtrix_5tt_rf/sub_308_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-308_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-309_mrtrix_5tt_rf/sub_309_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-309_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-310_mrtrix_5tt_rf/sub_310_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-310_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-311_mrtrix_5tt_rf/sub_311_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-311_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-312_mrtrix_5tt_rf/sub_312_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-312_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-314_mrtrix_5tt_rf/sub_314_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-314_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-315_mrtrix_5tt_rf/sub_315_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-315_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-316_mrtrix_5tt_rf/sub_316_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-316_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-352_mrtrix_5tt_rf/sub_352_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-352_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-353_mrtrix_5tt_rf/sub_353_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-353_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-358_mrtrix_5tt_rf/sub_358_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-358_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-361_mrtrix_5tt_rf/sub_361_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-361_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-362_mrtrix_5tt_rf/sub_362_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-362_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-363_mrtrix_5tt_rf/sub_363_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-363_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-364_mrtrix_5tt_rf/sub_364_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-364_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-365_mrtrix_5tt_rf/sub_365_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-365_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-366_mrtrix_5tt_rf/sub_366_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-366_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-367_mrtrix_5tt_rf/sub_367_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-367_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-368_mrtrix_5tt_rf/sub_368_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-368_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-369_mrtrix_5tt_rf/sub_369_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-369_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-501_mrtrix_5tt_rf/sub_501_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-501_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-502_mrtrix_5tt_rf/sub_502_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-502_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-503_mrtrix_5tt_rf/sub_503_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-503_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-504_mrtrix_5tt_rf/sub_504_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-504_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-505_mrtrix_5tt_rf/sub_505_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-505_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-506_mrtrix_5tt_rf/sub_506_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-506_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-507_mrtrix_5tt_rf/sub_507_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-507_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-508_mrtrix_5tt_rf/sub_508_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-508_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-509_mrtrix_5tt_rf/sub_509_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-509_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-510_mrtrix_5tt_rf/sub_510_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-510_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-512_mrtrix_5tt_rf/sub_512_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-512_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-513_mrtrix_5tt_rf/sub_513_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-513_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-514_mrtrix_5tt_rf/sub_514_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-514_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-515_mrtrix_5tt_rf/sub_515_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-515_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-551_mrtrix_5tt_rf/sub_551_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-551_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-553_mrtrix_5tt_rf/sub_553_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-553_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-555_mrtrix_5tt_rf/sub_555_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-555_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-556_mrtrix_5tt_rf/sub_556_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-556_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-557_mrtrix_5tt_rf/sub_557_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-557_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-558_mrtrix_5tt_rf/sub_558_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-558_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-559_mrtrix_5tt_rf/sub_559_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-559_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-560_mrtrix_5tt_rf/sub_560_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-560_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-561_mrtrix_5tt_rf/sub_561_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-561_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-562_mrtrix_5tt_rf/sub_562_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-562_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-563_mrtrix_5tt_rf/sub_563_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-563_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-564_mrtrix_5tt_rf/sub_564_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-564_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-565_mrtrix_5tt_rf/sub_565_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-565_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-611_mrtrix_5tt_rf/sub_611_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-611_ses-V1_space-T1w_desc-preproc_dwi_gm.txt \
/fred/oz251/Mast/derivatives/LA/mrtrix/connectome/responsemean_gm.txt `# output: respons mean of 2 pt. Need to be calculated for all pt's and number of unique b-values need to be identical across all input files`

#responsmean gm responsemean inputs output [ options ](from mrtrix readthedocs) - NEED TO BE ADJUSTED TO INCLUDE ALL PARTICIPANTS
responsemean \
-force \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-301_mrtrix_5tt_rf/sub_301_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-301_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-302_mrtrix_5tt_rf/sub_302_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-302_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-303_mrtrix_5tt_rf/sub_303_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-303_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-304_mrtrix_5tt_rf/sub_304_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-304_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-305_mrtrix_5tt_rf/sub_305_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-305_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-306_mrtrix_5tt_rf/sub_306_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-306_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-307_mrtrix_5tt_rf/sub_307_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-307_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-308_mrtrix_5tt_rf/sub_308_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-308_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-309_mrtrix_5tt_rf/sub_309_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-309_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-310_mrtrix_5tt_rf/sub_310_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-310_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-311_mrtrix_5tt_rf/sub_311_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-311_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-312_mrtrix_5tt_rf/sub_312_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-312_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-314_mrtrix_5tt_rf/sub_314_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-314_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-315_mrtrix_5tt_rf/sub_315_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-315_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-316_mrtrix_5tt_rf/sub_316_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-316_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-352_mrtrix_5tt_rf/sub_352_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-352_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-353_mrtrix_5tt_rf/sub_353_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-353_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-358_mrtrix_5tt_rf/sub_358_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-358_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-361_mrtrix_5tt_rf/sub_361_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-361_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-362_mrtrix_5tt_rf/sub_362_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-362_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-363_mrtrix_5tt_rf/sub_363_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-363_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-364_mrtrix_5tt_rf/sub_364_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-364_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-365_mrtrix_5tt_rf/sub_365_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-365_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-366_mrtrix_5tt_rf/sub_366_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-366_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-367_mrtrix_5tt_rf/sub_367_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-367_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-368_mrtrix_5tt_rf/sub_368_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-368_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-369_mrtrix_5tt_rf/sub_369_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-369_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-501_mrtrix_5tt_rf/sub_501_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-501_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-502_mrtrix_5tt_rf/sub_502_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-502_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-503_mrtrix_5tt_rf/sub_503_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-503_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-504_mrtrix_5tt_rf/sub_504_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-504_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-505_mrtrix_5tt_rf/sub_505_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-505_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-506_mrtrix_5tt_rf/sub_506_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-506_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-507_mrtrix_5tt_rf/sub_507_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-507_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-508_mrtrix_5tt_rf/sub_508_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-508_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-509_mrtrix_5tt_rf/sub_509_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-509_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-510_mrtrix_5tt_rf/sub_510_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-510_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-512_mrtrix_5tt_rf/sub_512_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-512_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-513_mrtrix_5tt_rf/sub_513_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-513_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-514_mrtrix_5tt_rf/sub_514_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-514_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-515_mrtrix_5tt_rf/sub_515_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-515_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-551_mrtrix_5tt_rf/sub_551_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-551_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-553_mrtrix_5tt_rf/sub_553_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-553_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-555_mrtrix_5tt_rf/sub_555_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-555_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-556_mrtrix_5tt_rf/sub_556_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-556_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-557_mrtrix_5tt_rf/sub_557_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-557_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-558_mrtrix_5tt_rf/sub_558_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-558_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-559_mrtrix_5tt_rf/sub_559_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-559_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-560_mrtrix_5tt_rf/sub_560_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-560_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-561_mrtrix_5tt_rf/sub_561_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-561_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-562_mrtrix_5tt_rf/sub_562_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-562_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-563_mrtrix_5tt_rf/sub_563_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-563_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-564_mrtrix_5tt_rf/sub_564_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-564_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-565_mrtrix_5tt_rf/sub_565_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-565_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/qsiprep/work/qsirecon_wf/sub-611_mrtrix_5tt_rf/sub_611_ses_V1_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_response/sub-611_ses-V1_space-T1w_desc-preproc_dwi_csf.txt \
/fred/oz251/Mast/derivatives/LA/mrtrix/connectome/responsemean_csf.txt `# output: respons mean of 2 pt. Need to be calculated for all pt's and number of unique b-values need to be identical across all input files`

#look at the meanRF (from BATMAN) - NEED TO BE ADJUSTED TO INCLUDE ALL PARTICIPANTS
shview /fred/oz251/Mast/derivatives/LA/mrtrix/connectome/responsemean_wm.txt `# Path/to_meanresponsfunction`
shview /fred/oz251/Mast/derivatives/LA/mrtrix/connectome/responsemean_gm.txt `# Path/to_meanresponsfunction`
shview /fred/oz251/Mast/derivatives/LA/mrtrix/connectome/responsemean_csf.txt `# Path/to_meanresponsfunction`